---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
script: bundle exec rake test
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="2.7.16"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="2.7.16"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="3.0.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="3.0.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="3.1.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="3.1.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="3.2.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="3.2.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="3.2.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="3.3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="3.3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="3.3.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="3.4.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="3.4.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="3.4.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="3.5.1"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="3.5.1"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="3.5.1"
  - rvm: 1.8.7
    env: 
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="3.6.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="3.6.0"
notifications:
  email: false
